ASSETS_DIR = assets
INCLUDE_DIR = include

.PHONY: assets
assets: $(INCLUDE_DIR)/index_html.h $(INCLUDE_DIR)/main_js.h $(INCLUDE_DIR)/styles_css.h $(INCLUDE_DIR)/favicon_ico.h $(INCLUDE_DIR)/assets_generated.h


define PY_GEN_HDR
python3 - <<'PY' > $@
from pathlib import Path
fn = Path("$<")
data = fn.read_bytes()
name = fn.stem.replace('.', '_')
var = Path("$@").stem
arr_name = var + "_data"
len_name = var + "_data_len"
print(f"unsigned char {arr_name}[] = {"{")
for i in range(0, len(data), 12):
    chunk = data[i:i+12]
    print(','.join('0x%02x' % b for b in chunk) + (',' if i+12 < len(data) else ''))
print('};')
print(f"unsigned int {len_name} = {len(data)};")
PY
endef

$(INCLUDE_DIR)/index_html.h: $(ASSETS_DIR)/index.html | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/index.html > $(INCLUDE_DIR)/index_html.h; \
	else \
		$(PY_GEN_HDR); \
	fi

$(INCLUDE_DIR)/main_js.h: $(ASSETS_DIR)/main.js | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/main.js > $(INCLUDE_DIR)/main_js.h; \
	else \
		$(PY_GEN_HDR); \
	fi

$(INCLUDE_DIR)/styles_css.h: $(ASSETS_DIR)/styles.css | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/styles.css > $(INCLUDE_DIR)/styles_css.h; \
	else \
		$(PY_GEN_HDR); \
	fi

$(INCLUDE_DIR)/favicon_ico.h: | $(INCLUDE_DIR)
	@if [ -f $(ASSETS_DIR)/favicon.ico ]; then \
		xxd -i $(ASSETS_DIR)/favicon.ico > $(INCLUDE_DIR)/favicon_ico.h; \
	else \
		printf '%s\n' '/* autogenerated empty favicon header (no assets/favicon.ico provided) */' 'unsigned char favicon_ico_data[] = { 0 };' 'unsigned int favicon_ico_data_len = 0;' > $(INCLUDE_DIR)/favicon_ico.h; \
	fi

$(INCLUDE_DIR)/assets_generated.h: ; @echo "/* generated by make assets */" > $(INCLUDE_DIR)/assets_generated.h; \
	 echo "#define USE_ASSET_HEADERS 1" >> $(INCLUDE_DIR)/assets_generated.h

$(INCLUDE_DIR):
	mkdir -p $(INCLUDE_DIR)

.PHONY: clean
clean:
	rm -f $(INCLUDE_DIR)/*.h
