ASSETS_DIR = assets
INCLUDE_DIR = include

.PHONY: assets
assets: $(INCLUDE_DIR)/index_html.h $(INCLUDE_DIR)/main_js.h $(INCLUDE_DIR)/styles_css.h $(INCLUDE_DIR)/favicon_ico.h $(INCLUDE_DIR)/assets_generated.h


# Python header generator (fallback for xxd)
# Moved to gen_header.py

$(INCLUDE_DIR)/index_html.h: $(ASSETS_DIR)/index.html | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/index.html > $(INCLUDE_DIR)/index_html.h; \
	else \
		python3 gen_header.py $(ASSETS_DIR)/index.html > $(INCLUDE_DIR)/index_html.h; \
	fi

$(INCLUDE_DIR)/main_js.h: $(ASSETS_DIR)/main.js | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/main.js > $(INCLUDE_DIR)/main_js.h; \
	else \
		python3 gen_header.py $(ASSETS_DIR)/main.js > $(INCLUDE_DIR)/main_js.h; \
	fi

$(INCLUDE_DIR)/styles_css.h: $(ASSETS_DIR)/styles.css | $(INCLUDE_DIR)
	@if command -v xxd >/dev/null 2>&1; then \
		xxd -i $(ASSETS_DIR)/styles.css > $(INCLUDE_DIR)/styles_css.h; \
	else \
		python3 gen_header.py $(ASSETS_DIR)/styles.css > $(INCLUDE_DIR)/styles_css.h; \
	fi

$(INCLUDE_DIR)/favicon_ico.h: | $(INCLUDE_DIR)
	@if [ -f $(ASSETS_DIR)/favicon.ico ]; then \
		xxd -i $(ASSETS_DIR)/favicon.ico > $(INCLUDE_DIR)/favicon_ico.h; \
	else \
		printf '%s\n' '/* autogenerated empty favicon header (no assets/favicon.ico provided) */' 'unsigned char favicon_ico_data[] = { 0 };' 'unsigned int favicon_ico_data_len = 0;' > $(INCLUDE_DIR)/favicon_ico.h; \
	fi

$(INCLUDE_DIR)/assets_generated.h: ; @echo "/* generated by make assets */" > $(INCLUDE_DIR)/assets_generated.h; \
	 echo "#define USE_ASSET_HEADERS 1" >> $(INCLUDE_DIR)/assets_generated.h

$(INCLUDE_DIR):
	mkdir -p $(INCLUDE_DIR)

.PHONY: clean
clean:
	rm -f $(INCLUDE_DIR)/*.h

# Compiler and simple build rules so `make` actually builds the daemon and helpers
CC ?= gcc
CFLAGS ?= -std=gnu11 -O2 -Wall -Wextra -pthread
LDFLAGS ?=

SRCS := cpu_throttle.c cpu_throttle_tui.c cpu_throttle_ctl.c
TARGETS := cpu_throttle cpu_throttle_tui cpu_throttle_ctl

.PHONY: all
.DEFAULT_GOAL := all
all: assets $(TARGETS)

.PHONY: test
test: all
	./tests/run_integration_tests.sh

cpu_throttle: assets cpu_throttle.c
	$(CC) $(CFLAGS) -o $@ cpu_throttle.c $(LDFLAGS)

cpu_throttle_tui: assets cpu_throttle_tui.c
	$(CC) $(CFLAGS) -o $@ cpu_throttle_tui.c -lncurses $(LDFLAGS)

cpu_throttle_ctl: assets cpu_throttle_ctl.c
	$(CC) $(CFLAGS) -o $@ cpu_throttle_ctl.c $(LDFLAGS)

